blog/main/routes.py
from Models import Post
from flask_login import login_user, current_user, login_required, logout_user
from flask import Blueprint, render_template, request
from blog.posts.forms import SearchForm


main = Blueprint('main', __name__)

@main.context_processor
def base():
    form=SearchForm
    return dict(form=form)

@main.route('/')
@main.route('/home')
def home_page():
    return render_template('home.html', title='Home')

@main.route('/admin/')
@login_required
def admin():
    return render_template('admin.html', title='Admin Page')


@main.route('/blogs')
@login_required
def blog_page():
    search_form = SearchForm()
    page=request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('blog.html', posts=posts, title='Blogs',search_form=search_form)

blog/posts/routes.py
from flask import Blueprint, abort, request, render_template, redirect, url_for, flash, get_flashed_messages
from flask_login import login_user, current_user, login_required, logout_user
from Models import User, Post
from blog import db, mail, ckeditor
from blog.posts.forms import PostForm, SearchForm
from blog.posts.utils import *


posts= Blueprint('posts', __name__)

@posts.route("/search_results")
def search_results():
        search_query = request.args.get('search', '')
 
        results = Post.query.filter(
        (Post.title.ilike(f"%{search_query}%")) |
        (Post.author.has(User.username.ilike(f"%{search_query}%"))) |
        (Post.content.ilike(f"%{search_query}%"))
    ).all()
        results = results.order_by(Post.title).all()
        return render_template('search_results.html', results=results, search_query=search_query)



@posts.route('/post/new', methods =['POST', 'GET'])
@login_required
def new_post():
    form=PostForm()
    if form.validate_on_submit():
        post=Post(title=form.title.data, image_file=save_picture_post(form.image_file.data), content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', category='success')
        return redirect(url_for('main.blog_page'))
    return render_template("new_post.html", form=form, title='New Post', legend='Create New Post')


@posts.route('/post/<int:post_id>', methods =['POST', 'GET'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('view_post.html',title=post.title, post=post, legend=' Post')


@posts.route('/post/<int:post_id>/update', methods =['POST', 'GET'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash('Your post has been updated!', category='success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data=post.title
        form.content.data=post.content
    return render_template('updatepost.html', form=form, title='Update Post', legend='Update Post')



@posts.route('/post/<int:post_id>/delete', methods =['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', category='success')
    return redirect(url_for('main.blog_page'))

blog/users/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, get_flashed_messages
from flask_login import login_user, current_user, login_required, logout_user
from Models import User, Post
from blog import db, mail
from werkzeug.security import generate_password_hash, check_password_hash
from blog.users.forms import RegisterForm, RequestResetForm, UpdateAccountForm, ResetPasswordForm, LoginForm
from blog.users.utils import *



users= Blueprint('users', __name__)


@users.route('/register', methods =['POST', 'GET'])
def register_page():
    if current_user.is_authenticated:
        return redirect(url_for('users.dashboard_page'))
    form = RegisterForm()
    if request.method == "POST" and form.validate_on_submit():
        username = form.username.data
        full_name = form.full_name.data
        email = form.email.data
        password = form.password.data
        gender = form.gender.data
        nationality = form.nationality.data

        # Hash the password before storing it
        hashed_password = generate_password_hash(password)

        # Create a new user and add to the database
        user_to_create = User(
            username=username,
            email=email,
            full_name=full_name,
            password_hash=hashed_password,
            image_file=save_picture(form.image_file.data),
            gender=gender,
            nationality=nationality,
        )
        
        db.session.add(user_to_create)
        db.session.commit()

         # Generate a confirmation token and send the verification email
        # confirmation_token = user_to_create.generate_confirmation_token()
        # confirmation_url = url_for('users.confirm_email', token=confirmation_token, _external=True)
        # send_verification_email(user_to_create, confirmation_url)

        flash(f"Registration successful! A confirmation email has been sent to {user_to_create.email}.", category='success')
        return redirect(url_for('users.login_page'))
        
    elif form.errors:
        for err_msg in form.errors.values():
            flash(f'{err_msg}', category='danger')

    return render_template('register.html', form=form, title='Register')


@users.route('/login', methods = ['POST', 'GET'])
def login_page():
    if current_user.is_authenticated:
        return redirect(url_for('users.dashboard_page'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        
        attempted_user = User.query.filter_by(username=username).first()
        if attempted_user and check_password_hash(attempted_user.password_hash, password):
            login_user(attempted_user, remember=form.remember_me.data)
            next_page = request.args.get('next')
            flash('Login Successful!', category='success')
            return redirect(next_page) if next_page else redirect(url_for('users.dashboard_page'))
        else:
            flash(f'Username and password do not match! Please try again', category='danger') 
    return render_template('login.html', form = form, title='Login')



@users.route('/logout')
def logout_page():
    logout_user()
    flash("You have been logged out, hope to see you soon!", category='info')
    return redirect(url_for('users.login_page'))



@users.route('/notifications')
@login_required
def notification_page():
    return render_template('notification.html', title='Notification')




@users.route('/dashboard', methods =['POST', 'GET'])
@login_required
def dashboard_page():
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('dashboard.html',title='Dashboard', image_file=image_file)



@users.route('/Update', methods =['POST', 'GET'])
@login_required
def update_page():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.image_file = save_picture(form.image_file.data)
        current_user.username=form.username.data
        current_user.email=form.email.data
        current_user.bio=form.bio.data
        db.session.commit()
        # Refresh the current user object after committing changes
        db.session.refresh(current_user)
        flash('Your account has been updated!', category='success')
        return redirect(url_for('users.dashboard_page'))
    elif request.method == 'GET':
        form.username.data=current_user.username
        form.email.data=current_user.email
        form.bio.data=current_user.bio
        
    return render_template('update account.html', title='Update Account', form=form)



@users.route('/user/<string:username>')
@login_required
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    
    # Use has method for relationship comparison
    posts = Post.query.filter(Post.author.has(id=user.id))\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    
    return render_template('user_posts.html', posts=posts, title='Blogs', user=user)


@users.route('/confirm/<token>')
def confirm_email(token):
    user = User.query.filter_by(confirmation_token=token).first()

    if user:
        if user.confirmed:
            flash('Email already confirmed. Please log in.', category='info')
        else:
            user.confirmed = True
            db.session.add(user)
            db.session.commit()
            flash('Email confirmed. You can now log in.', category='success')
    else:
        flash('Invalid or expired confirmation link. Please register again.', category='danger')

    return redirect(url_for('users.login_page'))

@users.route('/confirm')
@login_required
def resend_confirmation():
    token = current_user.generate_confirmation_token()
    send_email('auth/email/confirm','Confirm Your Account', user, token=token)
    flash('A new confirmation email has been sent to you by email.')
    return redirect(url_for('main.index'))


@users.route('/reset_password', methods =['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.dashboard_page'))
    form = RequestResetForm()
    if form.validate_on_submit:
        user=User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
            flash('An email has been sent with instructions to reset your password.', category='info')
            return redirect(url_for('users.login_page'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods =['POST', 'GET'])
def reset_token(token):
        if current_user.is_authenticated:
            return redirect(url_for('users.dashboard_page'))
        user = User.verify_reset_token(token)
        if user is None:
            flash('That is an invalid or expired token', category='warning')
            return redirect(url_for('users.reset_password'))
        form = ResetPasswordForm()
        if (form.validate_on_submit()):
            password = form.password.data
            # Hash the password before storing it
            hashed_password = generate_password_hash(password)
            user.password=hashed_password
            db.session.commit()
            flash("Password reset successful! You are now able log in.", category='success')
            return redirect(url_for('users.login_page'))
        return render_template('reset_token.html', title='Reset Password', form = form)

blog/templates/blog.html
{% extends 'layouts.html' %}

<!-- {% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/layouts.css')}}">
{% endblock %} -->


<body style="font-family: 'Arial', sans-serif;
background-color: #f8f8f8;
color: #333;">


{% block nav %}

  <header>
    <div class="logo">
      <h1 class="logo-text"><a href="{{url_for('main.home_page')}}" style="text-decoration: none;"><span>pRO</span>bLOg</a></h1>
    </div>

  <i class="fa-solid fa-bars menu-toggle" style="font-size: .8rem;"></i>

  <ul class="nav">
    {% if current_user.is_authenticated %}
      <li><a href="{{url_for('main.home_page')}}">Home</a></li> 
      <li>
          <a href="#">
              <i class="fa-regular fa-user" style="font-size: .8rem;"></i> {{ current_user.username }} <i class="fa-solid fa-chevron-down" style="font-size: .8rem;"></i></a>
          <ul>
              <li><a href="{{url_for('users.dashboard_page')}}">Dashboard</a></li>
              <li><a href="{{url_for('users.logout_page')}}" class="Logout">Log out</a></li>
          </ul>
        </li>
     


    {% else %}
      <li><a href="{{url_for('main.home_page')}}"> Home</a></li>
      <li><a href="{{url_for('users.login_page')}}">Sign in </a></li> 
      <li><a href="{{url_for('users.register_page')}}">Register</a></li> 

         
    {% endif%}
  </ul>
  </header>

{% endblock %}





{% block content %}
<h1 class="latest">Latest Blogs</h1>
<section class="search-sec"> 
  <form method="GET" action="{{ url_for('posts.search_results') }}" class="form-inline my-2 my-lg-0">
    {{ search_form.hidden_tag() }}
    {{ search_form.search(class="form-control-search") }}
    {{ search_form.submit(class="btn-outline-success") }}
  </form>
</section>

{% for post in posts.items %}              
<div class="blog-container">
  <article class="article-sec">
      <div class="author-detailsblog">
        <img class="author-profile-image" src="../static/profile_pics/{{ post.author.image_file }}" alt="Author Profile Picture">
        <a href="{{ url_for('users.user_post', username=post.author.username) }}" class="author-username">{{ post.author.username }}</a>
        <small class="date-posted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      </div>
          <br><br>
      
      <div>
        <img class="post-image" src="../static/UPLOAD_FOLDER/{{ post.image_file }}" alt="Post Image">
      </div>
      <div class="blog-details">
          <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" class="post-title">{{ post.title }}</a></h2>
          <p class="post-content">{{ post.content[:150]|safe }}{% if post.content|length > 150 %}...{% endif %}</p>
          <a href="{{ url_for('posts.post', post_id=post.id) }}" class="read-more">Read More</a>
      </div>
  </article>
</div>
{% endfor %}
</div>
<div class="pagination">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a href="{{ url_for('main.blog_page', page=page_num) }}" class="current">{{ page_num }}</a>
      {% else %}
        <a href="{{ url_for('main.blog_page', page=page_num) }}" class="">{{ page_num }}</a>
      {% endif %}  
    {% else %}
      <span class="ellipsis">...</span>  
    {% endif %}
  {% endfor %}
</div>

</body>
{% endblock %}












{% block footer%}
    <!-- Footer Section -->
<footer class="footer">
    <div class="footer-content">
        <div class="contact-us">
            <h3>Contact Us</h3>
            <p>If you have any questions or feedback, feel free to <a href="contact.html">contact us</a>.</p>
        </div>
        <div class="copyright">
            <p>&copy; 2023 Your Blog. All rights reserved.</p>
        </div>
    </div>
</footer>
{% endblock%}
</body>

blog/templates/dashboard.html
{% extends 'layouts.html' %}

<!-- {% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/layouts.css')}}">
{% endblock %} -->


{% block nav %}

<header>
  <div class="logo">
      <h1 class="logo-text"><a href="{{url_for('main.home_page')}}" style="text-decoration: none;"><span>pRO</span>bLOg</a></h1>
  </div>

  <i class="fa-solid fa-bars menu-toggle" style="font-size: .8rem;"></i>

  <ul class="nav">
    {% if current_user.is_authenticated %}
      {% if current_user.id == 1 %}
    <!-- Only show the Admin link for the user with id 1 -->
        <li><a href="{{url_for('main.admin')}}">Admin</a></li>
      {% endif %}
      <li><a href="{{url_for('main.home_page')}}">Home</a></li> 
      <li><a href="{{url_for('main.blog_page')}}">Blogs</a></li>
      <li><a href="{{url_for('users.update_page')}}">Account Settings</a></li>
      <li><a href="{{url_for('posts.new_post')}}">New Post</a></li>
      <li><a href="{{url_for('users.logout_page')}}" class="Logout">Log out</a></li>
    {% else %}
      <li><a href="{{url_for('main.home_page')}}"> Home</a></li>
      <li><a href="{{url_for('users.login_page')}}">Sign in </a></li> 
      <li><a href="{{url_for('users.register_page')}}">Register</a></li>   
    {% endif %}

  </ul>
</header>

{% endblock %}

<!--src="{{ url_for('static', filename='images/default.jpg') }}"-->
{% block content %}
    <body>
        <section id="profile">
          <div class="alignment">
            <h2>Welcome, {{ current_user.username }}!</h2>
            <div class="profile-image-container">
              <img class="profile-image" src="../static/profile_pics/{{ current_user.image_file }}" alt="Profile Picture">

            </div>
          
            <div class="user-info">
                <p>User ID: {{ current_user.id }}</p>
                <p>Email: {{ current_user.email }}</p>
                <p>Date of birth: {{ current_user.date_of_birth }}</p>
                <p>Nationality: {{ current_user.nationality }}</p>
                <p>Gender: {{ current_user.gender }}</p>
                <p>Full Name: {{ current_user.full_name }}</p>
                <p>Bio: {{ current_user.bio }}</p>
                <strong><p>Date joined:</strong> {{ current_user.created_at.strftime('%Y-%m-%d') }}</p></strong>
            </div>
          </div>
        </section>
    </body>
{% endblock %}

blog/templates/update account.html
{% extends 'layouts.html' %}

<!-- {% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/layouts.css')}}">
{% endblock %} -->


{% block nav %}

<header>
    <div class="logo">
        <h1 class="logo-text"><a href="{{url_for('main.home_page')}}" style="text-decoration: none;"><span>pRO</span>bLOg</a></h1>
    </div>

    <i class="fa-solid fa-bars menu-toggle" style="font-size: .8rem;"></i>

    <ul class="nav">
      {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.blog_page')}}">Blog</a></li> 
        <li>
            <a href="#">
                <i class="fa-regular fa-user" style="font-size: .8rem;"></i> {{ current_user.username }} <i class="fa-solid fa-chevron-down" style="font-size: .8rem;"></i></a>
            <ul>
                <li><a href="{{url_for('users.dashboard_page')}}">Dashboard</a></li>
                <li><a href="{{url_for('users.logout_page')}}" class="Logout">Log out</a></li>
            </ul>
        </li>
    {% else %}
      <li><a href="{{url_for('main.home_page')}}"> Home</a></li>
      <li><a href="{{url_for('users.login_page')}}">Sign in </a></li> 
      <li><a href="{{url_for('users.register_page')}}">Register</a></li> 
    {% endif %}
  </header>
{% endblock %}




{% block content %}
<body style="text-align: center;">
    <div class="containerupdate updatemargin">
        <div class="container2">
            <h2>Update Account Information</h2><br>
        <form action="{{url_for('users.update_page')}}" method="POST" class="form-contain" style="color: white;" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

            
        

            <div class="form-group">
                {{ form.username.label(class="control-label") }}
                        <br>
                {% if form.username.errors %}
                    <ul class="errors">
                    {% for error in form.username.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% else %}
                    {{ form.username(class="form-control") }}
                {% endif %}
            </div>
    
            <div class="form-group">
                {{ form.email.label(class="control-label") }}
                        <br>
                {% if form.email.errors %}
                    <ul class="errors">
                    {% for error in form.email.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>


            <div class="form-group">
                {{ form.bio.label(class="control-label") }}
                        <br>
                {% if form.bio.errors %}
                    <ul class="errors">
                    {% for error in form.bio.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% else %}
                    {{ form.bio(class="form-control-bio") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.image_file.label(class="control-label") }}
               
                {{ form.image_file(class="form-control") }}
                
            </div>
                    
                    <br>
            <div class="form-group">
                {{ form.submit(class="btn") }}
            </div>
        </form>   
    </div>
</div>
</body>                   
{% endblock %}

blog/templates/user_posts.html
{% extends 'layouts.html' %}

<!-- 
{% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/layouts.css')}}">
{% endblock %} -->




{% block nav %}

<header>
    <div class="logo">
        <h1 class="logo-text"><a href="{{url_for('main.home_page')}}" style="text-decoration: none;"><span>pRO</span>bLOg</a></h1>
    </div>

    <i class="fa-solid fa-bars menu-toggle" style="font-size: .8rem;"></i>

    <ul class="nav">
      {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.blog_page')}}">Blog</a></li> 
        <li>
            <a href="#">
                <i class="fa-regular fa-user" style="font-size: .8rem;"></i> {{ current_user.username }} <i class="fa-solid fa-chevron-down" style="font-size: .8rem;"></i></a>
            <ul>
                <li><a href="{{url_for('users.dashboard_page')}}">Dashboard</a></li>
                <li><a href="{{url_for('users.logout_page')}}" class="Logout">Log out</a></li>
            </ul>
        </li>
      {% else %}
        <li><a href="{{url_for('main.home_page')}}"> Home</a></li>
        <li><a href="{{url_for('users.login_page')}}">Sign in </a></li> 
        <li><a href="{{url_for('users.register_page')}}">Register</a></li> 
  
            <!--
              <li>
          <a href="#">
              <i class="fa fa-user"></i>
              pRO bLOg
              <i class="fa fa-chevron-down" style="font-size: .8em;"></i>
          </a>
          <ul>
            <li><a href="Notif.html">Notifications</a></li>
            <li><a href="#" class="Logout">Logout</a></li>
            -->
      {% endif%}
    </ul>
  </header>

{% endblock %}









{% block content %}
{% for post in posts.items %}  
<div class="blog-container">
    <article class="article-sec">
        <div class="author-detailsblog">
          <img class="author-profile-image" src="../static/profile_pics/{{ post.author.image_file }}" alt="Author Profile Picture">
          <a href="{{ url_for('users.user_post', username=post.author.username) }}" class="author-username">{{ post.author.username }}</a>
          <small class="date-posted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
            <br><br>
        
        <div>
          <img class="post-image" src="../static/UPLOAD_FOLDER/{{ post.image_file }}" alt="Post Image">
        </div>
        <div class="blog-details">
            <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" class="post-title">{{ post.title }}</a></h2>
            <p class="post-content">{{ post.content[:150]|safe }}{% if post.content|length > 150 %}...{% endif %}</p>
            <a href="{{ url_for('posts.post', post_id=post.id) }}" class="read-more">Read More</a>
        </div>
    </article>
</div>
  {% endfor %}
    <div class="pagination">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a href="{{ url_for('main.blog_page', page=page_num) }}" class="current">{{ page_num }}</a>
                {% else %}
                    <a href="{{ url_for('main.blog_page', page=page_num) }}" class="">{{ page_num }}</a>
                {% endif %}  
            {% else %}
                <span class="ellipsis">...</span>  
            {% endif %}
        {% endfor %}
    </div>







<!-- <div class="blog-parent posts-container">
    <h1 class="posts-header">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}              
    <div class="blog-container">
      <article class="article-sec">
          <div class="author-details">
              <div class="top-row">
                <img class="author-profile-image" src="../static/profile_pics/{{ post.author.image_file }}" alt="Author Profile Picture">
                  <a href="{{ url_for('users.user_post', username=post.author.username) }}" class="author-username">{{ post.author.username }}</a>
                  <small class="date-posted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
              <div class="second-row">
                <img class="post-image" src="{{ url_for('static', filename='UPLOAD_FOLDER/' + post.image_file) }}" alt="Post Image">
              </div>
          </div>
          <div class="blog-details">
              <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" class="post-title">{{ post.title }}</a></h2>
              <p class="post-content">{{ post.content[:150]|safe }}{% if post.content|length > 150 %}...{% endif %}</p>
              <a href="{{ url_for('posts.post', post_id=post.id) }}" class="read-more">Read More</a>
          </div>
      </article>
    </div>
    
    {% endfor %}
    </div>
 -->

<!---
        {% for post in posts.items %}
            <article class="post">
                <img class="author-profile-image" src="../static/profile_pics/{{ post.author.image_file }}" alt="Author Profile Picture">
                <div class="post-content">
                    <div class="post-meta">
                        <p class="author-username">{{ post.author.username }}</p>
                        <small class="post-date">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                    </div>
                    <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" class="post-title">{{ post.title }}</a></h2>
                    <p class="post-content">{{ post.content[:150]|safe }}{% if post.content|length > 150 %}...{% endif %}</p>
                    <a href="{{ url_for('posts.post', post_id=post.id) }}" class="read-more">Read More</a>
                </div>
            </article>
        {% endfor %}
        -->   
{% endblock %}











{% block footer%}
    <!-- Footer Section -->
<footer class="footer">
    <div class="footer-content">
        <div class="contact-us">
            <h3>Contact Us</h3>
            <!-- <p>If you have any questions or feedback, feel free to <a href="contact.html">contact us</a>.</p> -->
        </div>
        <div class="copyright">
            <p>&copy; 2023 Your Blog. All rights reserved.</p>
        </div>
    </div>
</footer>
{% endblock%}

blog/templates/view_post.html
{% extends 'layouts.html' %}

<!-- {% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/layouts.css')}}">
{% endblock %} -->


{% block nav %}

<header>
    <div class="logo">
        <h1 class="logo-text"><a href="{{url_for('main.home_page')}}" style="text-decoration: none;"><span>pRO</span>bLOg</a></h1>
    </div>

    <i class="fa-solid fa-bars menu-toggle" style="font-size: .8rem;"></i>

    <ul class="nav">
      {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.blog_page')}}">Blog</a></li> 
        <li>
            <a href="#">
                <i class="fa-regular fa-user" style="font-size: .8rem;"></i> {{ current_user.username }} <i class="fa-solid fa-chevron-down" style="font-size: .8rem;"></i></a>
            <ul>
                <li><a href="{{url_for('users.dashboard_page')}}">Dashboard</a></li>
                <li><a href="{{url_for('users.logout_page')}}" class="Logout">Log out</a></li>
            </ul>
        </li>

      {% else %}
        <li><a href="{{url_for('main.home_page')}}"> Home</a></li>
        <li><a href="{{url_for('users.login_page')}}">Sign in </a></li> 
        <li><a href="{{url_for('users.register_page')}}">Register</a></li> 
  
    
      {% endif%}
    </ul>
  </header>

{% endblock %}

{% block content %}
<div class="viewpost">
    <article>
        <div class="author-detailsblog">
          <img class="author-profile-image" src="../static/profile_pics/{{ post.author.image_file }}" alt="Author Profile Picture">
          <a href="{{ url_for('users.user_post', username=post.author.username) }}" class="author-username">{{ post.author.username }}</a>
          <small class="date-posted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
            <br><br>
       <!-- Current user can delete or update this post -->
{% if current_user == post.author %}
<a href="{{ url_for('posts.update_post', post_id=post.id) }}" style="background-color: blue; color: white; padding: 8px 16px; text-decoration: none; margin-right: 10px;">Update</a>
<button onclick="confirmDelete()" style="background-color: red; color: white; padding: 8px 16px; border: none; cursor: pointer;">Delete</button>
{% endif %}
        <div class="second-row">
          <img class="viewpost-image" src="../static/UPLOAD_FOLDER/{{ post.image_file }}" alt="Post Image">
        </div>
        <div class="blog-details">
            <h2 class="post-title">{{ post.title }}</h2>
            <p class="post-content">{{ post.content|safe }}</p>
        </div>
    </article>
  
</div>
  
<form id="deleteForm" action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST" style="display: none;">
    <input type="hidden" name="_method" value="DELETE">
</form>

<script>
    function confirmDelete() {
        if (confirm("Are you sure you want to delete this post?")) {
            document.getElementById('deleteForm').submit();
        }
    }
</script>

    </article>
{% endblock %}



















{% block footer%}
    <!-- Footer Section -->
<footer class="footer">
    <div class="footer-content">
        <div class="contact-us">
            <h3>Contact Us</h3>
            <p>If you have any questions or feedback, feel free to <a href="contact.html">contact us</a>.</p>
        </div>
        <div class="copyright">
            <p>&copy; 2023 Your Blog. All rights reserved.</p>
        </div>
    </div>
</footer>
{% endblock%}